### ISSUE TITLE
:comet: SOW: Additional Development and Customizations

### ISSUE THREAD

**Issue by aprilrieger** [scientist-softserv/archives_online#2]
## Summary
[SOW](https://docs.google.com/document/d/1f0aP5ZDUTj0S9RBN0jeDXT5nAYapszEdyG3wntO1FlI/edit)

> SoftServ will incorporate customizations following the gap analysis to bring the new ArcLight instance up to speed to .  
> 	If the option to upgrade in-place is chosen, then this time will be spent resolving dependencies and updating views, which is expected to be a significant effort in light of the UI changes in the new version.  This work is expected to continue in a phase under a subsequent SOW.
> 
> SoftServ allocates two sprints for this work.  A sprint consists of three full-time developers totalling 120 hours, plus additional QA and project management.  Additionally, SoftServ provisions up to 12 additional Senior Hours as needed.  
> 
> This SOW provisions the work as an initial phase, with a second phase available to complete work.

## Task
- [x] List of customizations is prioritized
- [x] 120 hours has been used towards incorporating customizations

## Customizations (in priority order)
- [x] #13
- [x] #26 
- [x] #17
- [x] #19
- [x] https://github.com/scientist-softserv/archives_online/issues/33
- [x] #20
- [x] #21
- [x] #22
- [x] #23
- [x] #24

## Won't do
- [x] #14
- [x] #15
- [x] #16
- [x] #18
- [x] #25
